# Generated by Django 3.0 on 2020-10-18 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jump',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('group_number', models.IntegerField(default=1, verbose_name='滑走グループ')),
                ('height', models.FloatField(default=0, verbose_name='高さ(km)')),
                ('distance', models.FloatField(default=0, verbose_name='幅(km)')),
                ('landing_speed', models.FloatField(default=0, verbose_name='着氷スピード(km/h)')),
                ('score', models.FloatField(default=0.0)),
            ],
        ),
    ]
