# Generated by Django 3.0 on 2020-11-01 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('figure_goe_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jump',
            name='free_or_short',
            field=models.IntegerField(choices=[(0, 'short_program'), (1, 'free_skating')], default=False, verbose_name='イベント'),
        ),
        migrations.AddField(
            model_name='jump',
            name='unique_entry',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=False, verbose_name='ジャンプの前の工夫'),
        ),
        migrations.AlterField(
            model_name='jump',
            name='distance',
            field=models.FloatField(default=0.0, verbose_name='幅(m)'),
        ),
        migrations.AlterField(
            model_name='jump',
            name='height',
            field=models.FloatField(default=0.0, verbose_name='高さ(m)'),
        ),
    ]
