# Generated by Django 3.0 on 2020-11-08 02:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('figure_goe_app', '0003_auto_20201101_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='jump',
            name='registered_date',
            field=models.DateField(default=datetime.date(2020, 11, 8)),
        ),
    ]
