# Generated by Django 3.0 on 2020-11-08 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('figure_goe_app', '0004_jump_registered_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='jump',
            name='comment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
